BINARY          := advisory
BUILD_DIR       := .
GO_FLAGS        := -trimpath -ldflags="-s -w"
LAMBDA_ZIP      := bootstrap.zip
LAMBDA_ZIP_ARM  := bootstrap-arm64.zip

# SECRET_ARN: ARN of the AWS Secrets Manager secret that holds application config.
# Resolution order (first non-empty value wins):
#   1. Command-line override:  SECRET_ARN=arn:aws:... make lambda
#   2. Local .env file:        SECRET_ARN=... in .env
#   3. Empty string:           env.sh is still generated but SECRET_ARN is unset;
#                              the application will fall back to S3 or system env vars.
SECRET_ARN      ?= $(shell grep -E '^SECRET_ARN=' .env 2>/dev/null | cut -d= -f2- | grep -v '^x\+$$')

# S3_ENV_BUCKET / S3_ENV_KEY: S3 source for the .env file (highest priority in AWS mode).
# Same resolution order as SECRET_ARN above.
# Values equal to the placeholder "xxxxxxxxxx" are treated as unset.
S3_ENV_BUCKET   ?= $(shell grep -E '^S3_ENV_BUCKET=' .env 2>/dev/null | cut -d= -f2- | grep -v '^x\+$$')
S3_ENV_KEY      ?= $(shell grep -E '^S3_ENV_KEY=' .env 2>/dev/null | cut -d= -f2- | grep -v '^x\+$$')
AWS_REGION      ?= $(shell grep -E '^AWS_REGION=' .env 2>/dev/null | cut -d= -f2- | grep -v '^x\+$$')

.PHONY: all run build clean test lint lambda lambda-arm64 _env_sh help

all: build

build:
	go build $(GO_FLAGS) -o $(BUILD_DIR)/$(BINARY) .

run: build
	npx @modelcontextprotocol/inspector ./$(BINARY)

test:
	go test ./test/... -v -count=1

lint:
	golangci-lint run ./...

# _env_sh: internal target — generates env.sh that Lambda's bootstrap wrapper sources
# at cold-start to export configuration identifiers into the process environment.
#
# env.sh only contains non-sensitive identifiers (ARN references, bucket names, region).
# Actual secret values are never written into the zip package.
#
# The file is always regenerated before each lambda / lambda-arm64 build and is
# removed by `make clean`.
_env_sh:
	@echo '#!/bin/sh'                                          >  env.sh
	@echo '# Auto-generated by Makefile — do not edit manually.' >> env.sh
	@echo '# Sources configuration identifiers at Lambda cold-start.' >> env.sh
	@if [ -n "$(SECRET_ARN)" ]; then \
		echo "export SECRET_ARN='$(SECRET_ARN)'"              >> env.sh; \
		echo "  [env.sh] SECRET_ARN=$(SECRET_ARN)"; \
	else \
		echo "  [env.sh] SECRET_ARN not set — skipped"; \
	fi
	@if [ -n "$(S3_ENV_BUCKET)" ]; then \
		echo "export S3_ENV_BUCKET='$(S3_ENV_BUCKET)'"        >> env.sh; \
		echo "  [env.sh] S3_ENV_BUCKET=$(S3_ENV_BUCKET)"; \
	fi
	@if [ -n "$(S3_ENV_KEY)" ]; then \
		echo "export S3_ENV_KEY='$(S3_ENV_KEY)'"              >> env.sh; \
		echo "  [env.sh] S3_ENV_KEY=$(S3_ENV_KEY)"; \
	fi
	@if [ -n "$(AWS_REGION)" ]; then \
		echo "export AWS_REGION='$(AWS_REGION)'"              >> env.sh; \
	fi
	@echo 'exec ./bootstrap "$$@"'                            >> env.sh
	@chmod +x env.sh

# lambda: build x86_64 Lambda deployment package.
#
# The zip contains two files:
#   bootstrap     — the Go binary (Lambda custom runtime entry point)
#   env.sh        — thin shell wrapper that exports config identifiers then
#                   exec's bootstrap; Lambda handler must be set to "env.sh"
#
# Usage:
#   make lambda                          # reads SECRET_ARN from .env
#   SECRET_ARN=arn:aws:... make lambda   # explicit override
lambda: _env_sh
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
		go build $(GO_FLAGS) -o bootstrap .
	zip -j $(LAMBDA_ZIP) bootstrap env.sh
	rm -f bootstrap env.sh
	@echo "Lambda deployment package ready (x86_64): $(LAMBDA_ZIP)"
	@echo "Set Lambda handler to: env.sh"

# lambda-arm64: build arm64 Lambda deployment package (Graviton2, lower cost).
#
# Usage:
#   make lambda-arm64
#   SECRET_ARN=arn:aws:... make lambda-arm64
lambda-arm64: _env_sh
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 \
		go build $(GO_FLAGS) -o bootstrap .
	zip -j $(LAMBDA_ZIP_ARM) bootstrap env.sh
	rm -f bootstrap env.sh
	@echo "Lambda deployment package ready (arm64): $(LAMBDA_ZIP_ARM)"
	@echo "Set Lambda handler to: env.sh"

clean:
	rm -f $(BUILD_DIR)/$(BINARY) bootstrap env.sh $(LAMBDA_ZIP) $(LAMBDA_ZIP_ARM)

help:
	@echo "Targets:"
	@echo "  build          Build local binary"
	@echo "  run            Build and launch MCP Inspector"
	@echo "  test           Run all tests"
	@echo "  lint           Run golangci-lint"
	@echo "  lambda         Build x86_64 Lambda zip (reads SECRET_ARN from .env)"
	@echo "  lambda-arm64   Build arm64 Lambda zip  (reads SECRET_ARN from .env)"
	@echo "  clean          Remove build artifacts"
	@echo ""
	@echo "Override example:"
	@echo "  SECRET_ARN=arn:aws:secretsmanager:ap-east-1:123:secret:name make lambda"
